title: Smart City Design 
description: Designing a smart city that is sustainable and efficient.
theme: jekyll-theme-slate

-title: Business Case Studies
url: https://01fe23bcs128.github.io/portfolio.github.io-./Business_case_studies
